#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v18
# autospec commit: f35655a
#
Name     : liblogging
Version  : 1.0.7
Release  : 12
URL      : https://github.com/rsyslog/liblogging/archive/v1.0.7/liblogging-1.0.7.tar.gz
Source0  : https://github.com/rsyslog/liblogging/archive/v1.0.7/liblogging-1.0.7.tar.gz
Summary  : RFC 3195 logging library
Group    : Development/Tools
License  : BSD-2-Clause
Requires: liblogging-bin = %{version}-%{release}
Requires: liblogging-lib = %{version}-%{release}
Requires: liblogging-license = %{version}-%{release}
Requires: liblogging-man = %{version}-%{release}
BuildRequires : file
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pypi-docutils
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description


%package bin
Summary: bin components for the liblogging package.
Group: Binaries
Requires: liblogging-license = %{version}-%{release}

%description bin
bin components for the liblogging package.


%package dev
Summary: dev components for the liblogging package.
Group: Development
Requires: liblogging-lib = %{version}-%{release}
Requires: liblogging-bin = %{version}-%{release}
Provides: liblogging-devel = %{version}-%{release}
Requires: liblogging = %{version}-%{release}

%description dev
dev components for the liblogging package.


%package lib
Summary: lib components for the liblogging package.
Group: Libraries
Requires: liblogging-license = %{version}-%{release}

%description lib
lib components for the liblogging package.


%package license
Summary: license components for the liblogging package.
Group: Default

%description license
license components for the liblogging package.


%package man
Summary: man components for the liblogging package.
Group: Default

%description man
man components for the liblogging package.


%prep
%setup -q -n liblogging-1.0.7
cd %{_builddir}/liblogging-1.0.7
pushd ..
cp -a liblogging-1.0.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724167833
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1724167833
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/liblogging
cp %{_builddir}/liblogging-%{version}/COPYING %{buildroot}/usr/share/package-licenses/liblogging/2942615ee26f9c8c1380d34e6ac7c3210c551437 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/stdlogctl
/usr/bin/stdlogctl

%files dev
%defattr(-,root,root,-)
/usr/include/liblogging/stdlog.h
/usr/lib64/liblogging-stdlog.so
/usr/lib64/pkgconfig/liblogging-stdlog.pc
/usr/share/man/man3/stdlog.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/liblogging-stdlog.so.0.1.0
/usr/lib64/liblogging-stdlog.so.0
/usr/lib64/liblogging-stdlog.so.0.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/liblogging/2942615ee26f9c8c1380d34e6ac7c3210c551437

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/stdlogctl.1
